### ISSUE TITLE
Low-level retries on resumable uploads always fail

### ISSUE THREAD

**Issue by actgardner** [GoogleCloudDataproc/hadoop-connectors#121] opened 2018-08-16 17:32 UTC
We've been getting errors from the GCS connector when resumable uploads fail: the initial call returns a 503, and the low-level retries obviously get a 410 because the `upload id` is no longer valid. 

These calls should have higher-level retries that generate a new upload ID.

```
16-08-2018 05:26:11 UTC parameters INFO - 18/08/16 05:26:10 INFO com.google.cloud.hadoop.util.RetryHttpInitializer: Encountered status code 503 when accessing URL https://www.googleapis.com/upload/storage/v1/b/<bucket>/o?ifGenerationMatch=0&name=<file>&uploadType=resumable&upload_id=<upload id>. Delegating to response handler for possible retry.

16-08-2018 05:26:12 UTC parameters INFO - 18/08/16 05:26:11 INFO com.google.cloud.hadoop.util.RetryHttpInitializer: Encountered status code 410 when accessing URL https://www.googleapis.com/upload/storage/v1/b/<bucket>/o?ifGenerationMatch=0&name=<path>&uploadType=resumable&upload_id=<upload id>. Delegating to response handler for possible retry.
16-08-2018 05:26:12 UTC parameters INFO - 18/08/16 05:26:11 ERROR com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel: Exception not convertible into handled response
16-08-2018 05:26:12 UTC parameters INFO - com.google.api.client.googleapis.json.GoogleJsonResponseException: 410 Gone
16-08-2018 05:26:12 UTC parameters INFO - {
16-08-2018 05:26:12 UTC parameters INFO -   "code" : 503,
16-08-2018 05:26:12 UTC parameters INFO -   "errors" : [ {
16-08-2018 05:26:12 UTC parameters INFO -     "domain" : "global",
16-08-2018 05:26:12 UTC parameters INFO -     "message" : "Backend Error",
16-08-2018 05:26:12 UTC parameters INFO -     "reason" : "backendError"
16-08-2018 05:26:12 UTC parameters INFO -   } ],
16-08-2018 05:26:12 UTC parameters INFO -   "message" : "Backend Error"
16-08-2018 05:26:12 UTC parameters INFO - }
```

**Comment by medb** [comment] 2019-10-18 17:04
Public tracker of the resolution of this issue in GCS: https://issuetracker.google.com/137168102

**Comment by j256** [comment] 2020-02-04 19:32
I've heard from Google on this.   To quote:

---------------------
As of right now, the issue is a bug and not a customer issue, and while a fix is on the way, there is a workaround that can be done on the customer’s side. The official workaround to circumvent 5xx and 410 errors is to implement retries, as was indicated in this comment from a Issue Tracker entry you have commented yourself  (see https://issuetracker.google.com/issues/137168102#comment2). The retry method recommendation can also be seen here (https://issuetracker.google.com/issues/35903805#comment2).

To retry successfully, catching 500 and 410 errors is required and, as the official documentation recommends (https://cloud.google.com/storage/docs/json_api/v1/status-codes#410_Gone), implementing a retry by starting a new session for the upload that received an unsuccessful status code but still needs uploading. The new session creation may be what was missing on your end, causing retries to be unsuccessful as you have mentioned previously. Additionally, exponential backoffs recommended in comments (see https://issuetracker.google.com/35903805#comment2) are the way to go to mitigate the issue (see https://cloud.google.com/storage/docs/exponential-backoff ).

**Comment by j256** [comment] 2020-02-04 19:34
My question is can we retry uploads of a particular file (from the start) so that it uses another underlying session?

**Comment by j256** [comment] 2020-02-04 19:41
For me it's not about caching data and resuming in the middle, it's about whether or not the HDFS API layer is holding onto the session which, according to google support (see below) needs to be reopened.  What we see that when we try to completely retry an upload from the start, we get the same GONE errors over and over.

I've heard from Google on the underlying problem.   To quote:

---------------------
As of right now, the issue is a bug and not a customer issue, and while a fix is on the way, there is a workaround that can be done on the customer’s side. The official workaround to circumvent 5xx and 410 errors is to implement retries, as was indicated in this comment from a Issue Tracker entry you have commented yourself  (see https://issuetracker.google.com/issues/137168102#comment2). The retry method recommendation can also be seen here (https://issuetracker.google.com/issues/35903805#comment2).

To retry successfully, catching 500 and 410 errors is required and, as the official documentation recommends (https://cloud.google.com/storage/docs/json_api/v1/status-codes#410_Gone), implementing a retry by starting a new session for the upload that received an unsuccessful status code but still needs uploading. The new session creation may be what was missing on your end, causing retries to be unsuccessful as you have mentioned previously. Additionally, exponential backoffs recommended in comments (see https://issuetracker.google.com/35903805#comment2) are the way to go to mitigate the issue (see https://cloud.google.com/storage/docs/exponential-backoff ).

**Comment by j256** [comment] 2020-02-04 22:31
This may have been fixed in the 1.9.X release.  We've not been able to upgrade to this until recently because of the Java 8 restrictions (don't ask).  See https://github.com/GoogleCloudDataproc/bigdata-interop/releases/tag/v1.9.0

More specifically:

>  10. Add more retries and error handling in GoogleCloudStorageReadChannel, to make it more resilient to network errors; also add a property to allow users to specify number of retries on low level GCS HTTP requests in case of server errors and I/O errors.

**Comment by j256** [comment] 2020-02-07 15:58
After pushing >100TB through the 1.9.17 version to GCS, I can say that the problem still exists.  It doesn't feel to me that anything is being retried looking at the failure timings.  It also looks like you can't just call the connector upload again in a loop because the underlying session is still corrupt.  So depressing!

**Comment by j256** [comment] 2020-02-09 19:02
After looking more closely at my log output, I found and fixed a bug in my retry logic and it now looks like 1.9.17 is working for me.  I am able to do a high-level retry because I'm caching the data locally – this wouldn't help if you were streaming.  I'm 100+TB into an upload run with 43 64MB chunks having to have been reuploaded.

**Comment by medb** [comment] 2020-02-09 20:52
`410 gone` response could not be retried by connector, because it can retry only a single request, not whole upload session.

May you share how exactly do you make retries on HDFS-level that lead to upload session reuse by GCS connector? (a code snippet that you use will be ideal).

**Comment by j256** [comment] 2020-02-10 16:22
Here's my snippet @medb .  I am uploading chunks of the file and then composing them at the end.  This allows me to completely create a new `GoogleHadoopOutputStream` over and over until it works.  Out of 2.67m uploads each of 64mb, my code had to retry 47.

```
CreateFileOptions tmpOptions = createFileOptions;
for (int i = 0; i < tries; i++) {
  if (i > 0 && !tmpOptions.overwriteExisting()) {
    // turn on overwriting since we are going to retry the upload and the file might exist
    tmpOptions = new CreateFileOptions(true /* turn on overwriting */, createFileOptions.getContentType(),
        createFileOptions.getAttributes(), createFileOptions.checkNoDirectoryConflict(),
        createFileOptions.ensureParentDirectoriesExist(), createFileOptions.getExistingGenerationId());
  }
  // see if we should backoff between retries
  long backoffMillis = i * retryBackoffMillis;
  if (backoffMillis > 0) {
    try {
      Thread.sleep(backoffMillis);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      return;
    }
  }
  long before = System.currentTimeMillis();
  try {
    try (InputStream is = outputStream.getInputStream();
        OutputStream gcsOutputStream = new GoogleHadoopOutputStream(ghfs, gcsPath, statistics, tmpOptions)) {
      IOUtils.copy(is, gcsOutputStream, false /* no close since it's done by the try () */);
    }
    return;
  } catch (IOException ioe) {
    if (first == null) {
      first = ioe;
    }
}
if (first != null) {
  throw new IOException("trying to upload part failed " + tries + " times: " + partPath, first);
}
```

**Comment by medb** [comment] 2020-02-10 17:05
@j256, are you able to complete 2.67m uploads with this code ? If no, what exception do you see? And how do you know that upload session is reused?

**Comment by j256** [comment] 2020-02-10 17:28
Yes I was able to upload 171TB with 2.67m each 64MB chunks with a bunch of threads working concurrently.  Multiple times did I see a whole slew of GONE errors that would happen but when retried, they would work.  I never saw a situation where it tried 3 times in a row.

> And how do you know that upload session is reused?

I don't know if it is being reused or not.  Is there anything that I can add to my logging to verify the session-id or something?

**Comment by medb** [comment] 2020-02-10 18:02
@j256, it seems that everything works as expected if uploads eventually succeed.

When #267 will be merged, session ID will be logged. But I'm confident that session is not reused because GCS connector doesn't store any state between uploads.

Suggestion - if each uploaded file/object is relatively small (< 128 MiB), it could be more reliable to use direct uploads instead of resumable uploads. You can enable direct upload with `fs.gs.outputstream.direct.upload.enable=true` property (supported in GCS connector 2.0.0+).

Any reason why you didn't use `hadoop disctp` or `gsutil` to upload data to GCS, and implemented your own solution instead?

**Comment by j256** [comment] 2020-02-10 18:35
Yeah, I don't want to go with 2.0.0 version for obvious reasons.  I work for a very cautious company.

> Any reason why you didn't use hadoop disctp or gsutil to upload data to GCS, and implemented your own solution instead?

We aren't using hadoop but instead utilizing HDFS to support various cloud filesystems dynamically.  We also need the data to be streamed and highly concurrent so there's a lot more custom code in our output stream.

**Comment by medb** [comment] 2020-02-10 18:54
@j256, in this case you may try to increase upload chunk to 128 MiB - it will slightly increase performance and will reduce numbed of files that you upload from 2.67m to 1.335m which could improve reliability:

```
fs.gs.outputstream.upload.chunk.size=134217728
```

**Comment by j256** [comment] 2020-02-10 19:32
Thanks @medb .  I've done a crap-ton of tests looking at concurrency count and buffer and have settled on actually 32mb with our default concurrent.  If you get the chunk size too big, the threads have to wait too long and your concurrency numbers drop.  I've also done tests around memory versus disk buffering (local HDD versus SSD) and other settings.

**Closed** 2020-03-11 18:53 UTC
